DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;

CREATE TABLE IF NOT EXISTS posts(
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    text BLOB NOT NULL,
    image_path VARCHAR(256) NOT NULL,
    likes_count INTEGER NOT NULL,
    tags VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments(
    id BIGSERIAL PRIMARY KEY,
    post_id BIGINT NOT NULL,
    text VARCHAR(1000000000) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES posts(id)
);